### ISSUE TITLE
Projen new results in error and no project code.

### ISSUE THREAD

**Issue by mbonig** [functionless/functionless#195]
I tried running the following:

`npx projen new --from @functionless/projen`

I got an error:

```
Error: duplicate option "artifactsDirectory" in @functionless/projen.FunctionlessProject (already declared in NodeProjectOptions)
    at addOptions (/home/matt/node_modules/projen/lib/inventory.js:152:23)
    at addOptions (/home/matt/node_modules/projen/lib/inventory.js:188:13)
    at addOptions (/home/matt/node_modules/projen/lib/inventory.js:188:13)
    at addOptions (/home/matt/node_modules/projen/lib/inventory.js:188:13)
    at discoverOptions (/home/matt/node_modules/projen/lib/inventory.js:136:5)
    at toProjectType (/home/matt/node_modules/projen/lib/inventory.js:113:18)
    at Object.discover (/home/matt/node_modules/projen/lib/inventory.js:22:23)
    at newProjectFromModule (/home/matt/node_modules/projen/lib/cli/cmds/new.js:156:10)
    at Object.handler (/home/matt/node_modules/projen/lib/cli/cmds/new.js:69:20)
    at Object.runCommand (/home/matt/node_modules/projen/node_modules/yargs/build/index.cjs:446:48)

```

**Comment by sam-goodwin** [comment]
Looks like a bug in our projen. https://github.com/functionless/functionless-projen

@brendo-m i think you tested this, right?

**Comment by brendo-m** [comment]
I did. Let me dig into it

**Comment by thantos** [comment]
Which version of projen?

What I am seeing.

`└── projen@0.52.75`

**Comment by sam-goodwin** [comment]
@mbonig what version of `projen` and `jsii` are installed in your global `npm` modules?

**Comment by mbonig** [comment]
`npx projen --version`:  0.57.3

i don't have jsii installed globally.

**Comment by thantos** [comment]
Thanks @mbonig. I was able to run a fresh install using `npx` with version `0.57.7` (npm 8.9, node 18).

> npx projen new --from @functionless/projen

1. What version of node and npm?
2. Anything unique about your system?
2. Have you run the command again?

**Comment by mbonig** [comment]
Hmm, nothing comes to mind

```
$ node --version
v14.17.5
$ yarn --version
1.22.10
```

Not sure what's going on, but now when I run it:

```
$ npx projen --version
0.31.19
```
I'll get that updated and it should fix things...
